// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class EmailHistory
{
    public Guid EntryId { get; set; }

    public string Sender { get; set; }

    public string RecipientEmail { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public bool IsSuccessful { get; set; }

    public DateTime CreatedDateTime { get; set; }
}