// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Message
{
    public Guid MessesageId { get; set; }

    public string PersonName { get; set; }

    public string Email { get; set; }

    public string Message1 { get; set; }

    public DateTime CreatedDateTime { get; set; }
}